# Question 1 

In [2]:
list=[]

In [11]:
for x in range(2000,3201) :
    if (x%7==0) and (x%5!=0):
        list.append(x)
                

In [9]:
for x in range(2000,3201) :
    if (x%7==0) and (x%5!=0):
        print(x , end=" ")

2002 2009 2016 2023 2037 2044 2051 2058 2072 2079 2086 2093 2107 2114 2121 2128 2142 2149 2156 2163 2177 2184 2191 2198 2212 2219 2226 2233 2247 2254 2261 2268 2282 2289 2296 2303 2317 2324 2331 2338 2352 2359 2366 2373 2387 2394 2401 2408 2422 2429 2436 2443 2457 2464 2471 2478 2492 2499 2506 2513 2527 2534 2541 2548 2562 2569 2576 2583 2597 2604 2611 2618 2632 2639 2646 2653 2667 2674 2681 2688 2702 2709 2716 2723 2737 2744 2751 2758 2772 2779 2786 2793 2807 2814 2821 2828 2842 2849 2856 2863 2877 2884 2891 2898 2912 2919 2926 2933 2947 2954 2961 2968 2982 2989 2996 3003 3017 3024 3031 3038 3052 3059 3066 3073 3087 3094 3101 3108 3122 3129 3136 3143 3157 3164 3171 3178 3192 3199 

# Question 2 

In [15]:
fact=1
n=8
for x in range (1,n+1) :
    fact=fact*x


In [16]:
print(fact, end=" ")

40320 

# Question 3 

In [6]:
n=int(input("Enter un entier :"))
d = {}
for i in range(1,n+1):
    d[i] = i * i
print (d)

Enter un entier :5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


# Question6

In [39]:
x = '''g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj. bbbb map'''



y=''

for i in x :
    if 'a' <= i <= 'z' :
             c = ord(i) + 2
             if c > ord('z') :
                     c -= 26
             y = y+  chr(c)

    else :
        y =y+ i
print(y)         
    

i hope you didnt translate it by hand. thats what computers are for. doing it in by hand is inefficient and that's why this text is so long. using string.maketrans() is recommended. now apply on the url. dddd ocr


# Question 7

In [11]:
import numpy as np
x= np.array([0, 1, 2, 3, 4, 5])
print(x)
print("Array to list:")
L=x.tolist()
print(L)

[0 1 2 3 4 5]
Array to list:
[0, 1, 2, 3, 4, 5]


# Question 8 

In [7]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("array1:")
print(x)
print("array2:")
print(y)
print("Covariance of the 2 arrays:")
np.cov(x, y)

array1:
[0 1 2]
array2:
[2 1 0]
Covariance of the 2 arrays:


array([[ 1., -1.],
       [-1.,  1.]])

# Question 5 

In [53]:
def missing_char(ch,n):
    ch2=""
    for i in range(len(ch)) :
        if i !=n : 
           # ch=ch.replace(ch[i], "") 
            ch2=ch2+ch[i]
       
    return (ch2) 

missing_char('katt',2)

'kat'

# Question 4 

In [5]:
import math
l = input().split(',') 
def calculer(D):
    C = 50
    H = 30
    return int(math.sqrt((2*C*D)/H))

for i in l :
    e=int(i)
    print(calculer(e), end=',')
    

    



100,150,180
18,22,24,